-- ============================================================
-- 醉社平台 — 商品导入Schema迁移
-- 日期: 2026-06-24
-- ============================================================

-- 1. category表添加 external_id
ALTER TABLE "category" ADD COLUMN IF NOT EXISTS "external_id" VARCHAR(50);
COMMENT ON COLUMN "category"."external_id" IS '平台类目ID（如400000790）';

-- 2. spu表添加商品平台字段
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "platform_sku_code" VARCHAR(50);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "platform_category_id" VARCHAR(50);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "barcode" VARCHAR(100);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "gross_weight" DECIMAL(10,2);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "weight_unit" VARCHAR(20);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "min_purchase_qty" INT DEFAULT 1;
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "delivery_mode" VARCHAR(20);
ALTER TABLE "spu" ADD COLUMN IF NOT EXISTS "spec_attributes" JSONB;

COMMENT ON COLUMN "spu"."platform_sku_code" IS '平台SKU编码';
COMMENT ON COLUMN "spu"."platform_category_id" IS '平台类目ID';
COMMENT ON COLUMN "spu"."barcode" IS '条形码';
COMMENT ON COLUMN "spu"."gross_weight" IS '毛重';
COMMENT ON COLUMN "spu"."weight_unit" IS '重量单位';
COMMENT ON COLUMN "spu"."min_purchase_qty" IS '最小起购数';
COMMENT ON COLUMN "spu"."delivery_mode" IS '发货模式';
COMMENT ON COLUMN "spu"."spec_attributes" IS '规格属性JSON（品牌、酒精度等）';

-- 3. 店内分类表
CREATE TABLE IF NOT EXISTS "inner_category" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id" BIGINT DEFAULT 0,
    "name" VARCHAR(100) NOT NULL,
    "sort_order" INT DEFAULT 0,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "inner_category" IS '店内分类表（商家自定义分类层级）';
COMMENT ON COLUMN "inner_category"."parent_id" IS '父级ID，0为一级分类';
COMMENT ON COLUMN "inner_category"."name" IS '分类名称';

-- 4. SPU与店内分类关联表
CREATE TABLE IF NOT EXISTS "spu_inner_category" (
    "spu_id" BIGINT NOT NULL REFERENCES "spu"("id") ON DELETE CASCADE,
    "inner_category_id" BIGINT NOT NULL REFERENCES "inner_category"("id") ON DELETE CASCADE,
    PRIMARY KEY ("spu_id", "inner_category_id")
);

COMMENT ON TABLE "spu_inner_category" IS 'SPU与店内分类多对多关联';
