-- ============================================================
-- 醉社平台 — PostgreSQL 数据库设计
-- DBMS: PostgreSQL 15+
-- 自动转换自 MySQL 8.0 语法
-- ============================================================

BEGIN;

-- -----------------------------------------------------------
-- sys_dict_type
-- -----------------------------------------------------------
CREATE TABLE "sys_dict_type" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dict_type" VARCHAR(100) NOT NULL,
    "dict_name" VARCHAR(100) NOT NULL,
    "status" SMALLINT DEFAULT 1,
    "remark" VARCHAR(500) DEFAULT '',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "sys_dict_type" IS '字典类型表';
COMMENT ON COLUMN "sys_dict_type"."dict_type" IS '字典类型编码';
COMMENT ON COLUMN "sys_dict_type"."dict_name" IS '字典类型名称';
COMMENT ON COLUMN "sys_dict_type"."status" IS '状态 0停用 1启用';
COMMENT ON COLUMN "sys_dict_type"."remark" IS '备注';
ALTER TABLE "sys_dict_type" ADD CONSTRAINT "uk_sys_dict_type_dict_type" UNIQUE ("dict_type");

-- -----------------------------------------------------------
-- sys_dict_data
-- -----------------------------------------------------------
CREATE TABLE "sys_dict_data" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dict_type" VARCHAR(100) NOT NULL,
    "dict_label" VARCHAR(100) NOT NULL,
    "dict_value" VARCHAR(100) NOT NULL,
    "sort" INTEGER DEFAULT 0,
    "status" SMALLINT DEFAULT 1,
    "remark" VARCHAR(500) DEFAULT '',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "sys_dict_data" IS '字典数据表';
COMMENT ON COLUMN "sys_dict_data"."dict_type" IS '字典类型编码';
COMMENT ON COLUMN "sys_dict_data"."dict_label" IS '字典标签';
COMMENT ON COLUMN "sys_dict_data"."dict_value" IS '字典值';
COMMENT ON COLUMN "sys_dict_data"."sort" IS '排序';
COMMENT ON COLUMN "sys_dict_data"."status" IS '状态';
COMMENT ON COLUMN "sys_dict_data"."remark" IS '备注';
CREATE INDEX "idx_sys_dict_data_dict_type" ON "sys_dict_data" ("dict_type");

-- -----------------------------------------------------------
-- sys_region
-- -----------------------------------------------------------
CREATE TABLE "sys_region" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id" BIGINT DEFAULT 0,
    "region_name" VARCHAR(100) NOT NULL,
    "region_level" SMALLINT NOT NULL,
    "region_code" VARCHAR(20),
    "sort" INTEGER DEFAULT 0
);

COMMENT ON TABLE "sys_region" IS '区域字典表';
COMMENT ON COLUMN "sys_region"."parent_id" IS '父级ID';
COMMENT ON COLUMN "sys_region"."region_name" IS '区域名称';
COMMENT ON COLUMN "sys_region"."region_level" IS '层级 1省 2市 3区/县';
COMMENT ON COLUMN "sys_region"."region_code" IS '行政区划代码';
CREATE INDEX "idx_sys_region_parent" ON "sys_region" ("parent_id");

-- -----------------------------------------------------------
-- company
-- -----------------------------------------------------------
CREATE TABLE "company" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "company_name" VARCHAR(200) NOT NULL,
    "company_type" VARCHAR(20) NOT NULL,
    "credit_code" VARCHAR(50),
    "legal_person" VARCHAR(50),
    "contact_name" VARCHAR(50) NOT NULL,
    "contact_phone" VARCHAR(20) NOT NULL,
    "business_license" VARCHAR(500),
    "license_images" JSONB,
    "province_id" BIGINT,
    "city_id" BIGINT,
    "district_id" BIGINT,
    "address" VARCHAR(500),
    "longitude" DECIMAL(10,7),
    "latitude" DECIMAL(10,7),
    "audit_status" VARCHAR(20) DEFAULT 'PENDING',
    "audit_remark" VARCHAR(500),
    "audit_at" TIMESTAMP,
    "audit_by" BIGINT,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "company" IS '公司/企业表（供应商+终端门店）';
COMMENT ON COLUMN "company"."company_name" IS '公司名称';
COMMENT ON COLUMN "company"."company_type" IS '公司类型: SUPPLIER供应商 / MERCHANT终端门店';
COMMENT ON COLUMN "company"."credit_code" IS '统一社会信用代码';
COMMENT ON COLUMN "company"."legal_person" IS '法人代表';
COMMENT ON COLUMN "company"."contact_name" IS '联系人姓名';
COMMENT ON COLUMN "company"."contact_phone" IS '联系人手机号';
COMMENT ON COLUMN "company"."business_license" IS '营业执照URL';
COMMENT ON COLUMN "company"."license_images" IS '资质图片列表';
COMMENT ON COLUMN "company"."province_id" IS '省';
COMMENT ON COLUMN "company"."city_id" IS '市';
COMMENT ON COLUMN "company"."district_id" IS '区';
COMMENT ON COLUMN "company"."address" IS '详细地址';
COMMENT ON COLUMN "company"."longitude" IS '经度（门店用于就近匹配）';
COMMENT ON COLUMN "company"."latitude" IS '纬度';
COMMENT ON COLUMN "company"."audit_status" IS '审核状态: PENDING待审核 / APPROVED通过 / REJECTED驳回';
COMMENT ON COLUMN "company"."audit_remark" IS '审核备注';
COMMENT ON COLUMN "company"."audit_at" IS '审核时间';
COMMENT ON COLUMN "company"."audit_by" IS '审核人';
COMMENT ON COLUMN "company"."status" IS '状态 0停用 1启用';
CREATE INDEX "idx_company_type" ON "company" ("company_type");
CREATE INDEX "idx_company_audit_status" ON "company" ("audit_status");
CREATE INDEX "idx_company_location" ON "company" ("city_id");

-- -----------------------------------------------------------
-- user
-- -----------------------------------------------------------
CREATE TABLE "user" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "company_id" BIGINT NOT NULL,
    "username" VARCHAR(50),
    "password" VARCHAR(200),
    "real_name" VARCHAR(50) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "wechat_openid" VARCHAR(100),
    "wechat_unionid" VARCHAR(100),
    "avatar_url" VARCHAR(500),
    "user_type" VARCHAR(20) NOT NULL,
    "is_master" SMALLINT DEFAULT 0,
    "status" SMALLINT DEFAULT 1,
    "last_login_at" TIMESTAMP,
    "last_login_ip" VARCHAR(50),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "user" IS '用户表';
COMMENT ON COLUMN "user"."company_id" IS '所属公司';
COMMENT ON COLUMN "user"."username" IS '用户名（子账号登录用）';
COMMENT ON COLUMN "user"."password" IS '密码（加密存储）';
COMMENT ON COLUMN "user"."real_name" IS '真实姓名';
COMMENT ON COLUMN "user"."phone" IS '手机号';
COMMENT ON COLUMN "user"."wechat_openid" IS '微信OpenID';
COMMENT ON COLUMN "user"."wechat_unionid" IS '微信UnionID';
COMMENT ON COLUMN "user"."avatar_url" IS '头像';
COMMENT ON COLUMN "user"."user_type" IS '用户类型: MASTER主账号 / SUB子账号';
COMMENT ON COLUMN "user"."is_master" IS '是否主账号 1是 0否';
COMMENT ON COLUMN "user"."status" IS '状态 0停用 1启用';
COMMENT ON COLUMN "user"."last_login_at" IS '最后登录时间';
COMMENT ON COLUMN "user"."last_login_ip" IS '最后登录IP';
ALTER TABLE "user" ADD CONSTRAINT "uk_user_phone" UNIQUE ("phone");
ALTER TABLE "user" ADD CONSTRAINT "uk_user_username" UNIQUE ("username");
CREATE INDEX "idx_user_company" ON "user" ("company_id");
CREATE INDEX "idx_user_openid" ON "user" ("wechat_openid");

-- -----------------------------------------------------------
-- role
-- -----------------------------------------------------------
CREATE TABLE "role" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(100) NOT NULL,
    "role_code" VARCHAR(50) NOT NULL,
    "role_level" SMALLINT DEFAULT 0,
    "company_id" BIGINT DEFAULT NULL,
    "data_scope" VARCHAR(20) DEFAULT 'ALL',
    "remark" VARCHAR(500) DEFAULT '',
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "role" IS '角色表（RBAC）';
COMMENT ON COLUMN "role"."role_name" IS '角色名称';
COMMENT ON COLUMN "role"."role_code" IS '角色编码';
COMMENT ON COLUMN "role"."role_level" IS '角色级别 0平台 1公司 2个人';
COMMENT ON COLUMN "role"."company_id" IS '所属公司（公司级角色）';
COMMENT ON COLUMN "role"."data_scope" IS '数据范围: ALL全部 / COMPANY本公司 / CUSTOM自定义';
COMMENT ON COLUMN "role"."remark" IS '备注';
ALTER TABLE "role" ADD CONSTRAINT "uk_role_role_code_company" UNIQUE ("role_code", "company_id");

-- -----------------------------------------------------------
-- permission
-- -----------------------------------------------------------
CREATE TABLE "permission" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id" BIGINT DEFAULT 0,
    "perm_name" VARCHAR(100) NOT NULL,
    "perm_code" VARCHAR(100),
    "perm_type" VARCHAR(20) NOT NULL,
    "menu_path" VARCHAR(200),
    "menu_icon" VARCHAR(100),
    "sort" INTEGER DEFAULT 0,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "permission" IS '权限表';
COMMENT ON COLUMN "permission"."parent_id" IS '父级ID';
COMMENT ON COLUMN "permission"."perm_name" IS '权限名称';
COMMENT ON COLUMN "permission"."perm_code" IS '权限编码（按钮级别用）';
COMMENT ON COLUMN "permission"."perm_type" IS '类型: MENU菜单 / BUTTON按钮';
COMMENT ON COLUMN "permission"."menu_path" IS '路由地址';
COMMENT ON COLUMN "permission"."menu_icon" IS '菜单图标';
COMMENT ON COLUMN "permission"."sort" IS '排序';
CREATE INDEX "idx_permission_parent" ON "permission" ("parent_id");
CREATE INDEX "idx_permission_code" ON "permission" ("perm_code");

-- -----------------------------------------------------------
-- role_permission
-- -----------------------------------------------------------
CREATE TABLE "role_permission" (
    "role_id" BIGINT NOT NULL,
    "perm_id" BIGINT NOT NULL,
    PRIMARY KEY ("role_id", "perm_id")
);

COMMENT ON TABLE "role_permission" IS '角色权限关联表';

-- -----------------------------------------------------------
-- user_role
-- -----------------------------------------------------------
CREATE TABLE "user_role" (
    "user_id" BIGINT NOT NULL,
    "role_id" BIGINT NOT NULL,
    PRIMARY KEY ("user_id", "role_id")
);

COMMENT ON TABLE "user_role" IS '用户角色关联表';

-- -----------------------------------------------------------
-- sub_account_scope
-- -----------------------------------------------------------
CREATE TABLE "sub_account_scope" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "scope_type" VARCHAR(20) NOT NULL,
    "scope_value" BIGINT NOT NULL
);

COMMENT ON TABLE "sub_account_scope" IS '子账号数据权限范围';
COMMENT ON COLUMN "sub_account_scope"."user_id" IS '子账号ID';
COMMENT ON COLUMN "sub_account_scope"."scope_type" IS '范围类型: WAREHOUSE仓库 / REGION区域';
COMMENT ON COLUMN "sub_account_scope"."scope_value" IS '范围值（仓库ID或区域ID）';
CREATE INDEX "idx_sub_account_scope_user" ON "sub_account_scope" ("user_id");

-- -----------------------------------------------------------
-- category
-- -----------------------------------------------------------
CREATE TABLE "category" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id" BIGINT DEFAULT 0,
    "cat_name" VARCHAR(100) NOT NULL,
    "cat_icon" VARCHAR(500),
    "sort" INTEGER DEFAULT 0,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "category" IS '商品分类表（白酒/啤酒/葡萄酒等）';
COMMENT ON COLUMN "category"."parent_id" IS '父级ID';
COMMENT ON COLUMN "category"."cat_name" IS '分类名称';
COMMENT ON COLUMN "category"."cat_icon" IS '分类图标';
COMMENT ON COLUMN "category"."sort" IS '排序';
CREATE INDEX "idx_category_parent" ON "category" ("parent_id");

-- -----------------------------------------------------------
-- brand
-- -----------------------------------------------------------
CREATE TABLE "brand" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "brand_name" VARCHAR(100) NOT NULL,
    "brand_logo" VARCHAR(500),
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "brand" IS '品牌表';
COMMENT ON COLUMN "brand"."brand_name" IS '品牌名称';
COMMENT ON COLUMN "brand"."brand_logo" IS '品牌Logo';
ALTER TABLE "brand" ADD CONSTRAINT "uk_brand_brand_name" UNIQUE ("brand_name");

-- -----------------------------------------------------------
-- spu
-- -----------------------------------------------------------
CREATE TABLE "spu" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category_id" BIGINT NOT NULL,
    "brand_id" BIGINT,
    "spu_name" VARCHAR(200) NOT NULL,
    "spec" VARCHAR(200),
    "unit" VARCHAR(20) DEFAULT '箱',
    "cover_image" VARCHAR(500),
    "images" JSONB,
    "description" TEXT,
    "alcohol_content" DECIMAL(5,2),
    "shelf_life_months" INTEGER,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "spu" IS '商品SPU表';
COMMENT ON COLUMN "spu"."category_id" IS '商品分类';
COMMENT ON COLUMN "spu"."brand_id" IS '品牌';
COMMENT ON COLUMN "spu"."spu_name" IS '商品名称';
COMMENT ON COLUMN "spu"."spec" IS '规格（500ml/750ml等）';
COMMENT ON COLUMN "spu"."unit" IS '单位（箱/瓶）';
COMMENT ON COLUMN "spu"."cover_image" IS '封面图';
COMMENT ON COLUMN "spu"."images" IS '商品图片列表';
COMMENT ON COLUMN "spu"."description" IS '商品描述';
COMMENT ON COLUMN "spu"."alcohol_content" IS '酒精度';
COMMENT ON COLUMN "spu"."shelf_life_months" IS '保质期(月)，NULL表示无固定保质期（如白酒长期保存）';
COMMENT ON COLUMN "spu"."status" IS '状态 0下架 1上架';
CREATE INDEX "idx_spu_category" ON "spu" ("category_id");
CREATE INDEX "idx_spu_brand" ON "spu" ("brand_id");

-- -----------------------------------------------------------
-- supplier_product
-- -----------------------------------------------------------
CREATE TABLE "supplier_product" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_id" BIGINT NOT NULL,
    "spu_id" BIGINT NOT NULL,
    "product_name" VARCHAR(200) NOT NULL,
    "cover_image" VARCHAR(500),
    "base_price" DECIMAL(12,2) NOT NULL,
    "min_order_qty" INTEGER DEFAULT 1,
    "status" VARCHAR(20) DEFAULT 'ON_SHELF',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "supplier_product" IS '供应商商品/SKU表';
COMMENT ON COLUMN "supplier_product"."supplier_id" IS '供应商公司ID';
COMMENT ON COLUMN "supplier_product"."spu_id" IS '商品SPU ID';
COMMENT ON COLUMN "supplier_product"."product_name" IS '供应商自定义商品名';
COMMENT ON COLUMN "supplier_product"."cover_image" IS '商品配图';
COMMENT ON COLUMN "supplier_product"."base_price" IS '基础售价（元）';
COMMENT ON COLUMN "supplier_product"."min_order_qty" IS '最小起订量';
COMMENT ON COLUMN "supplier_product"."status" IS '状态: ON_SHELF上架 / OFF_SHELF下架';
CREATE INDEX "idx_supplier_product_supplier" ON "supplier_product" ("supplier_id");
CREATE INDEX "idx_supplier_product_spu" ON "supplier_product" ("spu_id");
CREATE INDEX "idx_supplier_product_status" ON "supplier_product" ("status");

-- -----------------------------------------------------------
-- price_tier
-- -----------------------------------------------------------
CREATE TABLE "price_tier" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_product_id" BIGINT NOT NULL,
    "min_qty" INTEGER NOT NULL,
    "max_qty" INTEGER NOT NULL,
    "unit_price" DECIMAL(12,2) NOT NULL,
    "sort" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "price_tier" IS '商品阶梯价表';
COMMENT ON COLUMN "price_tier"."supplier_product_id" IS '供应商商品ID';
COMMENT ON COLUMN "price_tier"."min_qty" IS '最低购买数量';
COMMENT ON COLUMN "price_tier"."max_qty" IS '最高购买数量';
COMMENT ON COLUMN "price_tier"."unit_price" IS '阶梯单价（元）';
COMMENT ON COLUMN "price_tier"."sort" IS '档位排序';
CREATE INDEX "idx_price_tier_product" ON "price_tier" ("supplier_product_id");

-- -----------------------------------------------------------
-- bundle
-- -----------------------------------------------------------
CREATE TABLE "bundle" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_id" BIGINT NOT NULL,
    "bundle_name" VARCHAR(200) NOT NULL,
    "bundle_image" VARCHAR(500),
    "bundle_price" DECIMAL(12,2) NOT NULL,
    "bundle_desc" TEXT,
    "status" VARCHAR(20) DEFAULT 'ON_SHELF',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "bundle" IS '商品套餐表';
COMMENT ON COLUMN "bundle"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "bundle"."bundle_name" IS '套餐名称';
COMMENT ON COLUMN "bundle"."bundle_image" IS '套餐图片';
COMMENT ON COLUMN "bundle"."bundle_price" IS '套餐售价';
COMMENT ON COLUMN "bundle"."bundle_desc" IS '套餐描述';
COMMENT ON COLUMN "bundle"."status" IS '状态: ON_SHELF上架 / OFF_SHELF下架';
CREATE INDEX "idx_bundle_supplier" ON "bundle" ("supplier_id");
CREATE INDEX "idx_bundle_status" ON "bundle" ("status");

-- -----------------------------------------------------------
-- bundle_product
-- -----------------------------------------------------------
CREATE TABLE "bundle_product" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bundle_id" BIGINT NOT NULL,
    "supplier_product_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL
);

COMMENT ON TABLE "bundle_product" IS '套餐商品明细表';
COMMENT ON COLUMN "bundle_product"."bundle_id" IS '套餐ID';
COMMENT ON COLUMN "bundle_product"."supplier_product_id" IS '供应商商品ID';
COMMENT ON COLUMN "bundle_product"."quantity" IS '数量';
CREATE INDEX "idx_bundle_product_bundle" ON "bundle_product" ("bundle_id");

-- -----------------------------------------------------------
-- quotation
-- -----------------------------------------------------------
CREATE TABLE "quotation" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_id" BIGINT NOT NULL,
    "user_id" BIGINT NOT NULL,
    "quotation_no" VARCHAR(50) NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "source_type" VARCHAR(20) NOT NULL,
    "content_text" TEXT,
    "attachment_urls" JSONB,
    "status" VARCHAR(20) DEFAULT 'PUBLISHED',
    "archived_at" TIMESTAMP,
    "archived_by" BIGINT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "quotation" IS '报价单表';
COMMENT ON COLUMN "quotation"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "quotation"."user_id" IS '提交人ID';
COMMENT ON COLUMN "quotation"."quotation_no" IS '报价单号';
COMMENT ON COLUMN "quotation"."title" IS '报价标题';
COMMENT ON COLUMN "quotation"."source_type" IS '来源: TEXT文本 / IMAGE图片 / EXCEL表格';
COMMENT ON COLUMN "quotation"."content_text" IS '文本内容';
COMMENT ON COLUMN "quotation"."attachment_urls" IS '附件列表（图片/Excel）';
COMMENT ON COLUMN "quotation"."status" IS '状态: PUBLISHED已发布 / ARCHIVED已归档';
COMMENT ON COLUMN "quotation"."archived_at" IS '归档时间';
COMMENT ON COLUMN "quotation"."archived_by" IS '归档人';
ALTER TABLE "quotation" ADD CONSTRAINT "uk_quotation_quotation_no" UNIQUE ("quotation_no");
CREATE INDEX "idx_quotation_supplier" ON "quotation" ("supplier_id");
CREATE INDEX "idx_quotation_status" ON "quotation" ("status");

-- -----------------------------------------------------------
-- quotation_item
-- -----------------------------------------------------------
CREATE TABLE "quotation_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "quotation_id" BIGINT NOT NULL,
    "spu_id" BIGINT,
    "product_name" VARCHAR(200) NOT NULL,
    "spec" VARCHAR(100),
    "price" DECIMAL(12,2) NOT NULL,
    "stock_qty" INTEGER,
    "warehouse_id" BIGINT
);

COMMENT ON TABLE "quotation_item" IS '报价明细表';
COMMENT ON COLUMN "quotation_item"."quotation_id" IS '报价单ID';
COMMENT ON COLUMN "quotation_item"."spu_id" IS '商品SPU';
COMMENT ON COLUMN "quotation_item"."product_name" IS '商品名称';
COMMENT ON COLUMN "quotation_item"."spec" IS '规格';
COMMENT ON COLUMN "quotation_item"."price" IS '报价价格';
COMMENT ON COLUMN "quotation_item"."stock_qty" IS '库存数量';
COMMENT ON COLUMN "quotation_item"."warehouse_id" IS '所在仓库';
CREATE INDEX "idx_quotation_item_quotation" ON "quotation_item" ("quotation_id");

-- -----------------------------------------------------------
-- market_price
-- -----------------------------------------------------------
CREATE TABLE "market_price" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "spu_id" BIGINT NOT NULL,
    "price_date" DATE NOT NULL,
    "latest_price" DECIMAL(12,2),
    "highest_price" DECIMAL(12,2),
    "lowest_price" DECIMAL(12,2),
    "avg_price" DECIMAL(12,2),
    "change_percent" DECIMAL(8,2),
    "change_amount" DECIMAL(12,2),
    "supplier_count" INTEGER DEFAULT 0,
    "is_manual" SMALLINT DEFAULT 0,
    "remark" VARCHAR(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "market_price" IS '每日行情数据表';
COMMENT ON COLUMN "market_price"."spu_id" IS '商品SPU';
COMMENT ON COLUMN "market_price"."price_date" IS '行情日期';
COMMENT ON COLUMN "market_price"."latest_price" IS '最新报价（当日最低）';
COMMENT ON COLUMN "market_price"."highest_price" IS '当日最高价';
COMMENT ON COLUMN "market_price"."lowest_price" IS '当日最低价';
COMMENT ON COLUMN "market_price"."avg_price" IS '当日均价';
COMMENT ON COLUMN "market_price"."change_percent" IS '涨跌幅(%)';
COMMENT ON COLUMN "market_price"."change_amount" IS '涨跌金额';
COMMENT ON COLUMN "market_price"."supplier_count" IS '报价供应商数';
COMMENT ON COLUMN "market_price"."is_manual" IS '是否人工干预 1是 0否';
COMMENT ON COLUMN "market_price"."remark" IS '备注（干预原因）';
CREATE INDEX "idx_market_price_spu_date" ON "market_price" ("spu_id", "price_date");
CREATE INDEX "idx_market_price_date" ON "market_price" ("price_date");

-- -----------------------------------------------------------
-- warehouse
-- -----------------------------------------------------------
CREATE TABLE "warehouse" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_name" VARCHAR(200) NOT NULL,
    "warehouse_code" VARCHAR(50) NOT NULL,
    "warehouse_type" VARCHAR(20) NOT NULL,
    "owner_id" BIGINT,
    "province_id" BIGINT,
    "city_id" BIGINT,
    "district_id" BIGINT,
    "address" VARCHAR(500),
    "longitude" DECIMAL(10,7) NOT NULL,
    "latitude" DECIMAL(10,7) NOT NULL,
    "contact_name" VARCHAR(50),
    "contact_phone" VARCHAR(20),
    "status" VARCHAR(20) DEFAULT 'ENABLED',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "warehouse" IS '仓库/分仓表';
COMMENT ON COLUMN "warehouse"."warehouse_name" IS '仓库名称';
COMMENT ON COLUMN "warehouse"."warehouse_code" IS '仓库编码';
COMMENT ON COLUMN "warehouse"."warehouse_type" IS '类型: PLATFORM平台仓 / SUPPLIER供应商仓 / SHARED共享仓';
COMMENT ON COLUMN "warehouse"."owner_id" IS '归属方ID（供应商或平台）';
COMMENT ON COLUMN "warehouse"."province_id" IS '省';
COMMENT ON COLUMN "warehouse"."city_id" IS '市';
COMMENT ON COLUMN "warehouse"."district_id" IS '区';
COMMENT ON COLUMN "warehouse"."address" IS '详细地址';
COMMENT ON COLUMN "warehouse"."longitude" IS '经度';
COMMENT ON COLUMN "warehouse"."latitude" IS '纬度';
COMMENT ON COLUMN "warehouse"."contact_name" IS '仓库联系人';
COMMENT ON COLUMN "warehouse"."contact_phone" IS '仓库联系电话';
COMMENT ON COLUMN "warehouse"."status" IS '状态: ENABLED启用 / DISABLED停用';
CREATE INDEX "idx_warehouse_owner" ON "warehouse" ("owner_id");
CREATE INDEX "idx_warehouse_type" ON "warehouse" ("warehouse_type");
CREATE INDEX "idx_warehouse_city" ON "warehouse" ("city_id");
CREATE INDEX "idx_warehouse_location" ON "warehouse" ("longitude", "latitude");

-- -----------------------------------------------------------
-- warehouse_stock
-- -----------------------------------------------------------
CREATE TABLE "warehouse_stock" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_id" BIGINT NOT NULL,
    "supplier_product_id" BIGINT NOT NULL,
    "stock_qty" INTEGER NOT NULL DEFAULT 0,
    "locked_qty" INTEGER DEFAULT 0,
    "min_stock_alert" INTEGER DEFAULT 0,
    "production_date" DATE,
    "version" INTEGER DEFAULT 0,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "warehouse_stock" IS '仓库库存表';
COMMENT ON COLUMN "warehouse_stock"."warehouse_id" IS '仓库ID';
COMMENT ON COLUMN "warehouse_stock"."supplier_product_id" IS '供应商商品ID';
COMMENT ON COLUMN "warehouse_stock"."stock_qty" IS '库存数量';
COMMENT ON COLUMN "warehouse_stock"."locked_qty" IS '锁定库存（下单未支付）';
COMMENT ON COLUMN "warehouse_stock"."min_stock_alert" IS '库存预警下限';
COMMENT ON COLUMN "warehouse_stock"."production_date" IS '生产日期';
COMMENT ON COLUMN "warehouse_stock"."version" IS '乐观锁版本号';
ALTER TABLE "warehouse_stock" ADD CONSTRAINT "uk_warehouse_stock_warehouse_product" UNIQUE ("warehouse_id", "supplier_product_id");
CREATE INDEX "idx_warehouse_stock_product" ON "warehouse_stock" ("supplier_product_id");

-- -----------------------------------------------------------
-- warehouse_coverage
-- -----------------------------------------------------------
CREATE TABLE "warehouse_coverage" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "warehouse_id" BIGINT NOT NULL,
    "coverage_type" VARCHAR(20) NOT NULL,
    "max_distance" INTEGER,
    "region_ids" JSONB,
    "geo_fence_data" JSONB,
    "delivery_fee" DECIMAL(10,2) DEFAULT 0,
    "free_delivery_min" DECIMAL(12,2) DEFAULT 0,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "warehouse_coverage" IS '仓库配送范围表';
COMMENT ON COLUMN "warehouse_coverage"."warehouse_id" IS '仓库ID';
COMMENT ON COLUMN "warehouse_coverage"."coverage_type" IS '类型: DISTANCE按距离 / AREA按区域';
COMMENT ON COLUMN "warehouse_coverage"."max_distance" IS '最大配送距离（米）';
COMMENT ON COLUMN "warehouse_coverage"."region_ids" IS '配送区域ID列表';
COMMENT ON COLUMN "warehouse_coverage"."geo_fence_data" IS '地理围栏坐标（多边形顶点）';
COMMENT ON COLUMN "warehouse_coverage"."delivery_fee" IS '配送费';
COMMENT ON COLUMN "warehouse_coverage"."free_delivery_min" IS '免配送费最低金额';
CREATE INDEX "idx_warehouse_coverage_warehouse" ON "warehouse_coverage" ("warehouse_id");

-- -----------------------------------------------------------
-- transfer_order
-- -----------------------------------------------------------
CREATE TABLE "transfer_order" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transfer_no" VARCHAR(50) NOT NULL,
    "from_warehouse_id" BIGINT NOT NULL,
    "to_warehouse_id" BIGINT NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "transfer_type" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) DEFAULT 'PENDING',
    "total_qty" INTEGER DEFAULT 0,
    "total_amount" DECIMAL(12,2) DEFAULT 0,
    "remark" VARCHAR(500),
    "created_by" BIGINT,
    "completed_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "transfer_order" IS '调拨单表';
COMMENT ON COLUMN "transfer_order"."transfer_no" IS '调拨单号';
COMMENT ON COLUMN "transfer_order"."from_warehouse_id" IS '调出仓库';
COMMENT ON COLUMN "transfer_order"."to_warehouse_id" IS '调入仓库';
COMMENT ON COLUMN "transfer_order"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "transfer_order"."transfer_type" IS '类型: INTER_WAREHOUSE仓间 / TO_OFFLINE转线下';
COMMENT ON COLUMN "transfer_order"."status" IS '状态: PENDING待处理 / APPROVED已通过 / COMPLETED已完成 / CANCELLED已取消';
COMMENT ON COLUMN "transfer_order"."total_qty" IS '调拨总数量';
COMMENT ON COLUMN "transfer_order"."total_amount" IS '调拨总金额';
COMMENT ON COLUMN "transfer_order"."remark" IS '备注';
COMMENT ON COLUMN "transfer_order"."created_by" IS '创建人';
COMMENT ON COLUMN "transfer_order"."completed_at" IS '完成时间';
ALTER TABLE "transfer_order" ADD CONSTRAINT "uk_transfer_order_transfer_no" UNIQUE ("transfer_no");
CREATE INDEX "idx_transfer_order_from" ON "transfer_order" ("from_warehouse_id");
CREATE INDEX "idx_transfer_order_to" ON "transfer_order" ("to_warehouse_id");
CREATE INDEX "idx_transfer_order_supplier" ON "transfer_order" ("supplier_id");

-- -----------------------------------------------------------
-- transfer_order_item
-- -----------------------------------------------------------
CREATE TABLE "transfer_order_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transfer_id" BIGINT NOT NULL,
    "supplier_product_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_price" DECIMAL(12,2)
);

COMMENT ON TABLE "transfer_order_item" IS '调拨明细表';
COMMENT ON COLUMN "transfer_order_item"."transfer_id" IS '调拨单ID';
COMMENT ON COLUMN "transfer_order_item"."supplier_product_id" IS '商品ID';
COMMENT ON COLUMN "transfer_order_item"."quantity" IS '调拨数量';
COMMENT ON COLUMN "transfer_order_item"."unit_price" IS '单价';
CREATE INDEX "idx_transfer_order_item_transfer" ON "transfer_order_item" ("transfer_id");

-- -----------------------------------------------------------
-- delivery_person
-- -----------------------------------------------------------
CREATE TABLE "delivery_person" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "supplier_id" BIGINT NOT NULL,
    "name" VARCHAR(50) NOT NULL,
    "phone" VARCHAR(20) NOT NULL,
    "status" VARCHAR(20) DEFAULT 'AVAILABLE',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "delivery_person" IS '配送员表';
COMMENT ON COLUMN "delivery_person"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "delivery_person"."name" IS '配送员姓名';
COMMENT ON COLUMN "delivery_person"."phone" IS '联系电话';
COMMENT ON COLUMN "delivery_person"."status" IS '状态: AVAILABLE空闲 / BUSY配送中 / OFFLINE离线';
CREATE INDEX "idx_delivery_person_supplier" ON "delivery_person" ("supplier_id");

-- -----------------------------------------------------------
-- delivery_order
-- -----------------------------------------------------------
CREATE TABLE "delivery_order" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "delivery_no" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "delivery_type" VARCHAR(20) NOT NULL,
    "delivery_person_id" BIGINT,
    "third_delivery_id" VARCHAR(100),
    "pickup_address" VARCHAR(500),
    "delivery_address" VARCHAR(500),
    "delivery_fee" DECIMAL(10,2) DEFAULT 0,
    "status" VARCHAR(20) DEFAULT 'PENDING',
    "estimated_arrival" TIMESTAMP,
    "actual_arrival" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "delivery_order" IS '配送单表';
COMMENT ON COLUMN "delivery_order"."delivery_no" IS '配送单号';
COMMENT ON COLUMN "delivery_order"."order_id" IS '关联订单';
COMMENT ON COLUMN "delivery_order"."delivery_type" IS '配送方式: SELF自行配送 / THIRD货拉拉';
COMMENT ON COLUMN "delivery_order"."delivery_person_id" IS '配送员ID';
COMMENT ON COLUMN "delivery_order"."third_delivery_id" IS '第三方配送单号';
COMMENT ON COLUMN "delivery_order"."pickup_address" IS '取货地址';
COMMENT ON COLUMN "delivery_order"."delivery_address" IS '收货地址';
COMMENT ON COLUMN "delivery_order"."delivery_fee" IS '配送费';
COMMENT ON COLUMN "delivery_order"."status" IS '状态: PENDING待取货 / PICKING取货中 / DELIVERING配送中 / COMPLETED已完成 / FAILED配送失败';
COMMENT ON COLUMN "delivery_order"."estimated_arrival" IS '预计送达时间';
COMMENT ON COLUMN "delivery_order"."actual_arrival" IS '实际送达时间';
ALTER TABLE "delivery_order" ADD CONSTRAINT "uk_delivery_order_delivery_no" UNIQUE ("delivery_no");
CREATE INDEX "idx_delivery_order_order" ON "delivery_order" ("order_id");
CREATE INDEX "idx_delivery_order_status" ON "delivery_order" ("status");

-- -----------------------------------------------------------
-- cart
-- -----------------------------------------------------------
CREATE TABLE "cart" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "cart" IS '购物车表（按供应商分组）';
COMMENT ON COLUMN "cart"."user_id" IS '用户ID';
COMMENT ON COLUMN "cart"."supplier_id" IS '供应商ID（购物车按供应商分组）';
ALTER TABLE "cart" ADD CONSTRAINT "uk_cart_user_supplier" UNIQUE ("user_id", "supplier_id");

-- -----------------------------------------------------------
-- cart_item
-- -----------------------------------------------------------
CREATE TABLE "cart_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cart_id" BIGINT NOT NULL,
    "supplier_product_id" BIGINT NOT NULL,
    "warehouse_id" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "selected" SMALLINT DEFAULT 1
);

COMMENT ON TABLE "cart_item" IS '购物车商品明细';
COMMENT ON COLUMN "cart_item"."cart_id" IS '购物车ID';
COMMENT ON COLUMN "cart_item"."supplier_product_id" IS '商品ID';
COMMENT ON COLUMN "cart_item"."warehouse_id" IS '来源仓库';
COMMENT ON COLUMN "cart_item"."quantity" IS '数量';
COMMENT ON COLUMN "cart_item"."selected" IS '是否选中 1是 0否';
ALTER TABLE "cart_item" ADD CONSTRAINT "uk_cart_item_cart_product" UNIQUE ("cart_id", "supplier_product_id");

-- -----------------------------------------------------------
-- order_info
-- -----------------------------------------------------------
CREATE TABLE "order_info" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_no" VARCHAR(50) NOT NULL,
    "buyer_id" BIGINT NOT NULL,
    "buyer_user_id" BIGINT NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "order_status" VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    "total_amount" DECIMAL(12,2) NOT NULL,
    "discount_amount" DECIMAL(12,2) DEFAULT 0,
    "delivery_fee" DECIMAL(10,2) DEFAULT 0,
    "pay_amount" DECIMAL(12,2) NOT NULL,
    "pay_status" VARCHAR(20) DEFAULT 'UNPAID',
    "pay_time" TIMESTAMP,
    "pay_channel" VARCHAR(20),
    "transaction_id" VARCHAR(100),
    "delivery_type" VARCHAR(20),
    "receiver_name" VARCHAR(50),
    "receiver_phone" VARCHAR(20),
    "receiver_address" VARCHAR(500),
    "buyer_remark" VARCHAR(500),
    "cancel_time" TIMESTAMP,
    "cancel_reason" VARCHAR(500),
    "complete_time" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "order_info" IS '订单主表';
COMMENT ON COLUMN "order_info"."order_no" IS '订单号';
COMMENT ON COLUMN "order_info"."buyer_id" IS '买方ID（门店公司ID）';
COMMENT ON COLUMN "order_info"."buyer_user_id" IS '下单人ID';
COMMENT ON COLUMN "order_info"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "order_info"."order_status" IS '订单状态';
COMMENT ON COLUMN "order_info"."total_amount" IS '商品总金额（原价）';
COMMENT ON COLUMN "order_info"."discount_amount" IS '优惠金额';
COMMENT ON COLUMN "order_info"."delivery_fee" IS '配送费';
COMMENT ON COLUMN "order_info"."pay_amount" IS '实付金额';
COMMENT ON COLUMN "order_info"."pay_status" IS '支付状态: UNPAID未支付 / PAID已支付 / REFUNDING退款中 / REFUNDED已退款';
COMMENT ON COLUMN "order_info"."pay_time" IS '支付时间';
COMMENT ON COLUMN "order_info"."pay_channel" IS '支付渠道: WECHAT微信 / ALIPAY支付宝';
COMMENT ON COLUMN "order_info"."transaction_id" IS '支付平台交易号';
COMMENT ON COLUMN "order_info"."delivery_type" IS '配送方式: SELF自行配送 / THIRD第三方';
COMMENT ON COLUMN "order_info"."receiver_name" IS '收货人';
COMMENT ON COLUMN "order_info"."receiver_phone" IS '收货电话';
COMMENT ON COLUMN "order_info"."receiver_address" IS '收货地址';
COMMENT ON COLUMN "order_info"."buyer_remark" IS '买家备注';
COMMENT ON COLUMN "order_info"."cancel_time" IS '取消时间';
COMMENT ON COLUMN "order_info"."cancel_reason" IS '取消原因';
COMMENT ON COLUMN "order_info"."complete_time" IS '完成时间（确认收货）';
ALTER TABLE "order_info" ADD CONSTRAINT "uk_order_info_order_no" UNIQUE ("order_no");
CREATE INDEX "idx_order_info_buyer" ON "order_info" ("buyer_id");
CREATE INDEX "idx_order_info_supplier" ON "order_info" ("supplier_id");
CREATE INDEX "idx_order_info_status" ON "order_info" ("order_status");
CREATE INDEX "idx_order_info_pay_status" ON "order_info" ("pay_status");
CREATE INDEX "idx_order_info_created" ON "order_info" ("created_at");

-- -----------------------------------------------------------
-- order_item
-- -----------------------------------------------------------
CREATE TABLE "order_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "supplier_product_id" BIGINT NOT NULL,
    "warehouse_id" BIGINT NOT NULL,
    "product_name" VARCHAR(200) NOT NULL,
    "product_image" VARCHAR(500),
    "spec" VARCHAR(100),
    "production_date" DATE,
    "unit_price" DECIMAL(12,2) NOT NULL,
    "quantity" INTEGER NOT NULL,
    "tier_level" INTEGER,
    "sub_total" DECIMAL(12,2) NOT NULL
);

COMMENT ON TABLE "order_item" IS '订单明细表';
COMMENT ON COLUMN "order_item"."order_id" IS '订单ID';
COMMENT ON COLUMN "order_item"."supplier_product_id" IS '商品ID';
COMMENT ON COLUMN "order_item"."warehouse_id" IS '出库仓库ID';
COMMENT ON COLUMN "order_item"."product_name" IS '商品名称（快照）';
COMMENT ON COLUMN "order_item"."product_image" IS '商品图片（快照）';
COMMENT ON COLUMN "order_item"."spec" IS '规格';
COMMENT ON COLUMN "order_item"."production_date" IS '生产日期（快照）';
COMMENT ON COLUMN "order_item"."unit_price" IS '成交单价';
COMMENT ON COLUMN "order_item"."quantity" IS '数量';
COMMENT ON COLUMN "order_item"."tier_level" IS '命中的阶梯价档位';
COMMENT ON COLUMN "order_item"."sub_total" IS '小计';
CREATE INDEX "idx_order_item_order" ON "order_item" ("order_id");

-- -----------------------------------------------------------
-- payment_record
-- -----------------------------------------------------------
CREATE TABLE "payment_record" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "payment_no" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "pay_amount" DECIMAL(12,2) NOT NULL,
    "pay_channel" VARCHAR(20) NOT NULL,
    "transaction_id" VARCHAR(100),
    "pay_status" VARCHAR(20) NOT NULL,
    "pay_time" TIMESTAMP,
    "callback_data" JSONB,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "payment_record" IS '支付记录表';
COMMENT ON COLUMN "payment_record"."payment_no" IS '支付流水号';
COMMENT ON COLUMN "payment_record"."order_id" IS '订单ID';
COMMENT ON COLUMN "payment_record"."pay_amount" IS '支付金额';
COMMENT ON COLUMN "payment_record"."pay_channel" IS '支付渠道';
COMMENT ON COLUMN "payment_record"."transaction_id" IS '第三方交易号';
COMMENT ON COLUMN "payment_record"."pay_status" IS '状态: PROCESSING处理中 / SUCCESS成功 / FAILED失败 / CLOSED已关闭';
COMMENT ON COLUMN "payment_record"."pay_time" IS '支付时间';
COMMENT ON COLUMN "payment_record"."callback_data" IS '支付回调原始数据';
ALTER TABLE "payment_record" ADD CONSTRAINT "uk_payment_record_payment_no" UNIQUE ("payment_no");
CREATE INDEX "idx_payment_record_order" ON "payment_record" ("order_id");

-- -----------------------------------------------------------
-- refund
-- -----------------------------------------------------------
CREATE TABLE "refund" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "refund_no" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "buyer_id" BIGINT NOT NULL,
    "refund_amount" DECIMAL(12,2) NOT NULL,
    "refund_reason" VARCHAR(500),
    "refund_images" JSONB,
    "status" VARCHAR(20) DEFAULT 'PENDING_AUDIT',
    "audit_remark" VARCHAR(500),
    "audit_by" BIGINT,
    "audit_at" TIMESTAMP,
    "refund_time" TIMESTAMP,
    "refund_transaction_id" VARCHAR(100),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "refund" IS '退款表';
COMMENT ON COLUMN "refund"."refund_no" IS '退款单号';
COMMENT ON COLUMN "refund"."order_id" IS '订单ID';
COMMENT ON COLUMN "refund"."buyer_id" IS '申请人（门店）';
COMMENT ON COLUMN "refund"."refund_amount" IS '退款金额';
COMMENT ON COLUMN "refund"."refund_reason" IS '退款原因';
COMMENT ON COLUMN "refund"."refund_images" IS '退款凭证图片';
COMMENT ON COLUMN "refund"."status" IS '状态: PENDING_AUDIT待审核 / APPROVED已通过 / REJECTED已驳回 / PROCESSING退款中 / COMPLETED已完成';
COMMENT ON COLUMN "refund"."audit_remark" IS '审核备注';
COMMENT ON COLUMN "refund"."audit_by" IS '审核人';
COMMENT ON COLUMN "refund"."audit_at" IS '审核时间';
COMMENT ON COLUMN "refund"."refund_time" IS '实际退款时间';
COMMENT ON COLUMN "refund"."refund_transaction_id" IS '退款交易号';
ALTER TABLE "refund" ADD CONSTRAINT "uk_refund_refund_no" UNIQUE ("refund_no");
CREATE INDEX "idx_refund_order" ON "refund" ("order_id");
CREATE INDEX "idx_refund_status" ON "refund" ("status");

-- -----------------------------------------------------------
-- notification_template
-- -----------------------------------------------------------
CREATE TABLE "notification_template" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "template_code" VARCHAR(100) NOT NULL,
    "template_name" VARCHAR(200) NOT NULL,
    "template_type" VARCHAR(20) NOT NULL,
    "wechat_template_id" VARCHAR(100),
    "template_content" TEXT,
    "status" SMALLINT DEFAULT 1,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "notification_template" IS '消息模板表';
COMMENT ON COLUMN "notification_template"."template_code" IS '模板编码';
COMMENT ON COLUMN "notification_template"."template_name" IS '模板名称';
COMMENT ON COLUMN "notification_template"."template_type" IS '类型: WECHAT微信模板消息 / INNER站内信 / SMS短信';
COMMENT ON COLUMN "notification_template"."wechat_template_id" IS '微信模板ID';
COMMENT ON COLUMN "notification_template"."template_content" IS '模板内容（含变量占位）';
ALTER TABLE "notification_template" ADD CONSTRAINT "uk_notification_template_template_code" UNIQUE ("template_code");

-- -----------------------------------------------------------
-- notification
-- -----------------------------------------------------------
CREATE TABLE "notification" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "template_code" VARCHAR(100),
    "notify_type" VARCHAR(20) NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "content" TEXT NOT NULL,
    "channel" VARCHAR(20) NOT NULL,
    "biz_type" VARCHAR(50),
    "biz_id" BIGINT,
    "read_status" SMALLINT DEFAULT 0,
    "read_at" TIMESTAMP,
    "send_status" VARCHAR(20) DEFAULT 'PENDING',
    "send_result" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "notification" IS '消息通知表';
COMMENT ON COLUMN "notification"."user_id" IS '接收人';
COMMENT ON COLUMN "notification"."template_code" IS '模板编码';
COMMENT ON COLUMN "notification"."notify_type" IS '类型: ORDER订单 / DELIVERY配送 / MARKET行情 / REFUND退款 / SYSTEM系统';
COMMENT ON COLUMN "notification"."title" IS '通知标题';
COMMENT ON COLUMN "notification"."content" IS '通知内容';
COMMENT ON COLUMN "notification"."channel" IS '渠道: WECHAT微信 / INNER站内信';
COMMENT ON COLUMN "notification"."biz_type" IS '业务类型';
COMMENT ON COLUMN "notification"."biz_id" IS '业务ID（关联的订单/退款等ID）';
COMMENT ON COLUMN "notification"."read_status" IS '已读状态 0未读 1已读';
COMMENT ON COLUMN "notification"."read_at" IS '阅读时间';
COMMENT ON COLUMN "notification"."send_status" IS '发送状态: PENDING待发送 / SUCCESS成功 / FAILED失败';
COMMENT ON COLUMN "notification"."send_result" IS '发送结果';
CREATE INDEX "idx_notification_user_read" ON "notification" ("user_id", "read_status");
CREATE INDEX "idx_notification_type" ON "notification" ("notify_type");
CREATE INDEX "idx_notification_biz" ON "notification" ("biz_type", "biz_id");

-- -----------------------------------------------------------
-- operation_log
-- -----------------------------------------------------------
CREATE TABLE "operation_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "company_id" BIGINT,
    "module" VARCHAR(100),
    "operation" VARCHAR(100),
    "method" VARCHAR(200),
    "request_url" VARCHAR(500),
    "request_params" TEXT,
    "response_result" TEXT,
    "ip_address" VARCHAR(50),
    "user_agent" VARCHAR(500),
    "cost_time" BIGINT,
    "status" SMALLINT DEFAULT 1,
    "error_msg" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "operation_log" IS '操作日志表';
COMMENT ON COLUMN "operation_log"."user_id" IS '操作人';
COMMENT ON COLUMN "operation_log"."company_id" IS '所属公司';
COMMENT ON COLUMN "operation_log"."module" IS '操作模块';
COMMENT ON COLUMN "operation_log"."operation" IS '操作类型';
COMMENT ON COLUMN "operation_log"."method" IS '请求方法';
COMMENT ON COLUMN "operation_log"."request_url" IS '请求URL';
COMMENT ON COLUMN "operation_log"."request_params" IS '请求参数';
COMMENT ON COLUMN "operation_log"."response_result" IS '返回结果';
COMMENT ON COLUMN "operation_log"."ip_address" IS '操作IP';
COMMENT ON COLUMN "operation_log"."user_agent" IS '浏览器UA';
COMMENT ON COLUMN "operation_log"."cost_time" IS '耗时(ms)';
COMMENT ON COLUMN "operation_log"."status" IS '状态 0失败 1成功';
COMMENT ON COLUMN "operation_log"."error_msg" IS '错误信息';
CREATE INDEX "idx_operation_log_user" ON "operation_log" ("user_id");
CREATE INDEX "idx_operation_log_module" ON "operation_log" ("module");
CREATE INDEX "idx_operation_log_created" ON "operation_log" ("created_at");

-- -----------------------------------------------------------
-- system_config
-- -----------------------------------------------------------
CREATE TABLE "system_config" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "config_key" VARCHAR(100) NOT NULL,
    "config_value" TEXT,
    "config_desc" VARCHAR(500),
    "config_type" VARCHAR(20) DEFAULT 'STRING',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "system_config" IS '系统参数配置表';
COMMENT ON COLUMN "system_config"."config_key" IS '配置键';
COMMENT ON COLUMN "system_config"."config_value" IS '配置值';
COMMENT ON COLUMN "system_config"."config_desc" IS '配置说明';
COMMENT ON COLUMN "system_config"."config_type" IS '值类型: STRING / INT / BOOLEAN / JSON';
ALTER TABLE "system_config" ADD CONSTRAINT "uk_system_config_config_key" UNIQUE ("config_key");

-- -----------------------------------------------------------
-- wallet
-- -----------------------------------------------------------
CREATE TABLE "wallet" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "owner_id" BIGINT NOT NULL,
    "owner_type" VARCHAR(20) NOT NULL,
    "balance" DECIMAL(14,2) DEFAULT 0,
    "frozen_balance" DECIMAL(14,2) DEFAULT 0,
    "total_income" DECIMAL(14,2) DEFAULT 0,
    "total_outcome" DECIMAL(14,2) DEFAULT 0,
    "status" VARCHAR(20) DEFAULT 'ACTIVE',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "wallet" IS '钱包表（专业版）';
COMMENT ON COLUMN "wallet"."owner_id" IS '持有人ID（供应商或平台）';
COMMENT ON COLUMN "wallet"."owner_type" IS '类型: SUPPLIER供应商 / PLATFORM平台';
COMMENT ON COLUMN "wallet"."balance" IS '可用余额';
COMMENT ON COLUMN "wallet"."frozen_balance" IS '冻结余额';
COMMENT ON COLUMN "wallet"."total_income" IS '累计收入';
COMMENT ON COLUMN "wallet"."total_outcome" IS '累计支出';
COMMENT ON COLUMN "wallet"."status" IS '状态: ACTIVE正常 / FROZEN冻结';
ALTER TABLE "wallet" ADD CONSTRAINT "uk_wallet_owner" UNIQUE ("owner_id", "owner_type");
CREATE INDEX "idx_wallet_balance" ON "wallet" ("balance");

-- -----------------------------------------------------------
-- wallet_transaction
-- -----------------------------------------------------------
CREATE TABLE "wallet_transaction" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "transaction_no" VARCHAR(50) NOT NULL,
    "wallet_id" BIGINT NOT NULL,
    "transaction_type" VARCHAR(20) NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "balance_before" DECIMAL(14,2) NOT NULL,
    "balance_after" DECIMAL(14,2) NOT NULL,
    "biz_type" VARCHAR(50),
    "biz_id" BIGINT,
    "remark" VARCHAR(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "wallet_transaction" IS '钱包流水表（专业版）';
COMMENT ON COLUMN "wallet_transaction"."transaction_no" IS '流水号';
COMMENT ON COLUMN "wallet_transaction"."wallet_id" IS '钱包ID';
COMMENT ON COLUMN "wallet_transaction"."transaction_type" IS '类型: RECHARGE充值 / WITHDRAW提现 / SETTLEMENT结算 / REFUND退款 / FREEZE冻结 / UNFREEZE解冻';
COMMENT ON COLUMN "wallet_transaction"."amount" IS '金额（正数入账，负数出账）';
COMMENT ON COLUMN "wallet_transaction"."balance_before" IS '变动前余额';
COMMENT ON COLUMN "wallet_transaction"."balance_after" IS '变动后余额';
COMMENT ON COLUMN "wallet_transaction"."biz_type" IS '关联业务类型';
COMMENT ON COLUMN "wallet_transaction"."biz_id" IS '关联业务ID';
COMMENT ON COLUMN "wallet_transaction"."remark" IS '备注';
ALTER TABLE "wallet_transaction" ADD CONSTRAINT "uk_wallet_transaction_transaction_no" UNIQUE ("transaction_no");
CREATE INDEX "idx_wallet_transaction_wallet" ON "wallet_transaction" ("wallet_id");
CREATE INDEX "idx_wallet_transaction_biz" ON "wallet_transaction" ("biz_type", "biz_id");

-- -----------------------------------------------------------
-- settlement
-- -----------------------------------------------------------
CREATE TABLE "settlement" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "settlement_no" VARCHAR(50) NOT NULL,
    "order_id" BIGINT NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "settlement_amount" DECIMAL(12,2) NOT NULL,
    "settlement_status" VARCHAR(20) DEFAULT 'PENDING',
    "confirm_receipt_time" TIMESTAMP,
    "settle_due_date" DATE,
    "settle_time" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "settlement" IS '结算单表（专业版）';
COMMENT ON COLUMN "settlement"."settlement_no" IS '结算单号';
COMMENT ON COLUMN "settlement"."order_id" IS '订单ID';
COMMENT ON COLUMN "settlement"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "settlement"."settlement_amount" IS '结算金额';
COMMENT ON COLUMN "settlement"."settlement_status" IS '状态: PENDING待结算 / PROCESSING结算中 / COMPLETED已完成 / FAILED失败';
COMMENT ON COLUMN "settlement"."confirm_receipt_time" IS '确认收货时间';
COMMENT ON COLUMN "settlement"."settle_due_date" IS '结算到期日（T+3）';
COMMENT ON COLUMN "settlement"."settle_time" IS '实际结算时间';
ALTER TABLE "settlement" ADD CONSTRAINT "uk_settlement_settlement_no" UNIQUE ("settlement_no");
CREATE INDEX "idx_settlement_order" ON "settlement" ("order_id");
CREATE INDEX "idx_settlement_supplier" ON "settlement" ("supplier_id");
CREATE INDEX "idx_settlement_status_due" ON "settlement" ("settlement_status", "settle_due_date");

-- -----------------------------------------------------------
-- withdrawal
-- -----------------------------------------------------------
CREATE TABLE "withdrawal" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "withdrawal_no" VARCHAR(50) NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "wallet_id" BIGINT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "bank_name" VARCHAR(100),
    "bank_account" VARCHAR(50),
    "account_name" VARCHAR(50),
    "status" VARCHAR(20) DEFAULT 'PENDING_AUDIT',
    "audit_by" BIGINT,
    "audit_at" TIMESTAMP,
    "complete_at" TIMESTAMP,
    "remark" VARCHAR(500),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "withdrawal" IS '提现记录表（专业版）';
COMMENT ON COLUMN "withdrawal"."withdrawal_no" IS '提现单号';
COMMENT ON COLUMN "withdrawal"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "withdrawal"."wallet_id" IS '钱包ID';
COMMENT ON COLUMN "withdrawal"."amount" IS '提现金额';
COMMENT ON COLUMN "withdrawal"."bank_name" IS '银行名称';
COMMENT ON COLUMN "withdrawal"."bank_account" IS '银行账号';
COMMENT ON COLUMN "withdrawal"."account_name" IS '开户名';
COMMENT ON COLUMN "withdrawal"."status" IS '状态: PENDING_AUDIT待审核 / APPROVED已通过 / PROCESSING处理中 / COMPLETED已完成 / REJECTED已驳回';
COMMENT ON COLUMN "withdrawal"."audit_by" IS '审核人';
COMMENT ON COLUMN "withdrawal"."audit_at" IS '审核时间';
COMMENT ON COLUMN "withdrawal"."complete_at" IS '到账时间';
COMMENT ON COLUMN "withdrawal"."remark" IS '备注';
ALTER TABLE "withdrawal" ADD CONSTRAINT "uk_withdrawal_withdrawal_no" UNIQUE ("withdrawal_no");
CREATE INDEX "idx_withdrawal_supplier" ON "withdrawal" ("supplier_id");
CREATE INDEX "idx_withdrawal_status" ON "withdrawal" ("status");

-- -----------------------------------------------------------
-- third_party_delivery
-- -----------------------------------------------------------
CREATE TABLE "third_party_delivery" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "delivery_order_id" BIGINT NOT NULL,
    "platform" VARCHAR(20) NOT NULL,
    "third_order_no" VARCHAR(100),
    "estimate_fee" DECIMAL(10,2),
    "actual_fee" DECIMAL(10,2),
    "driver_name" VARCHAR(50),
    "driver_phone" VARCHAR(20),
    "vehicle_info" VARCHAR(200),
    "track_data" JSONB,
    "callback_raw" JSONB,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "third_party_delivery" IS '第三方配送记录表（专业版）';
COMMENT ON COLUMN "third_party_delivery"."delivery_order_id" IS '配送单ID';
COMMENT ON COLUMN "third_party_delivery"."platform" IS '平台: HUOLALA货拉拉';
COMMENT ON COLUMN "third_party_delivery"."third_order_no" IS '第三方平台订单号';
COMMENT ON COLUMN "third_party_delivery"."estimate_fee" IS '预估费用';
COMMENT ON COLUMN "third_party_delivery"."actual_fee" IS '实际费用';
COMMENT ON COLUMN "third_party_delivery"."driver_name" IS '司机姓名';
COMMENT ON COLUMN "third_party_delivery"."driver_phone" IS '司机电话';
COMMENT ON COLUMN "third_party_delivery"."vehicle_info" IS '车辆信息';
COMMENT ON COLUMN "third_party_delivery"."track_data" IS '轨迹数据';
COMMENT ON COLUMN "third_party_delivery"."callback_raw" IS '回调原始数据';
ALTER TABLE "third_party_delivery" ADD CONSTRAINT "uk_third_party_delivery_platform_order" UNIQUE ("platform", "third_order_no");
CREATE INDEX "idx_third_party_delivery_delivery" ON "third_party_delivery" ("delivery_order_id");

-- -----------------------------------------------------------
-- shared_warehouse_application
-- -----------------------------------------------------------
CREATE TABLE "shared_warehouse_application" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "application_no" VARCHAR(50) NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "warehouse_id" BIGINT,
    "capacity_required" INTEGER,
    "purpose" VARCHAR(500),
    "status" VARCHAR(20) DEFAULT 'PENDING_AUDIT',
    "audit_remark" VARCHAR(500),
    "audit_by" BIGINT,
    "audit_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "shared_warehouse_application" IS '共享仓申请表（专业版）';
COMMENT ON COLUMN "shared_warehouse_application"."application_no" IS '申请单号';
COMMENT ON COLUMN "shared_warehouse_application"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "shared_warehouse_application"."warehouse_id" IS '申请的共享仓ID';
COMMENT ON COLUMN "shared_warehouse_application"."capacity_required" IS '需求仓容（箱）';
COMMENT ON COLUMN "shared_warehouse_application"."purpose" IS '使用用途';
COMMENT ON COLUMN "shared_warehouse_application"."status" IS '状态: PENDING_AUDIT待审核 / APPROVED已通过 / REJECTED已驳回 / USING使用中 / RETURNED已归还';
COMMENT ON COLUMN "shared_warehouse_application"."audit_remark" IS '审核备注';
COMMENT ON COLUMN "shared_warehouse_application"."audit_by" IS '审核人';
COMMENT ON COLUMN "shared_warehouse_application"."audit_at" IS '审核时间';
ALTER TABLE "shared_warehouse_application" ADD CONSTRAINT "uk_shared_warehouse_application_application_no" UNIQUE ("application_no");
CREATE INDEX "idx_shared_warehouse_application_supplier" ON "shared_warehouse_application" ("supplier_id");
CREATE INDEX "idx_shared_warehouse_application_status" ON "shared_warehouse_application" ("status");

-- -----------------------------------------------------------
-- price_trend_cache
-- -----------------------------------------------------------
CREATE TABLE "price_trend_cache" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "spu_id" BIGINT NOT NULL,
    "period" VARCHAR(20) NOT NULL,
    "trend_data" JSONB,
    "generated_at" TIMESTAMP
);

COMMENT ON TABLE "price_trend_cache" IS '价格走势缓存表（专业版）';
COMMENT ON COLUMN "price_trend_cache"."spu_id" IS '商品SPU';
COMMENT ON COLUMN "price_trend_cache"."period" IS '周期: D30 / D90 / D180';
COMMENT ON COLUMN "price_trend_cache"."trend_data" IS '走势数据 [{date, price}, ...]';
COMMENT ON COLUMN "price_trend_cache"."generated_at" IS '生成时间';
ALTER TABLE "price_trend_cache" ADD CONSTRAINT "uk_price_trend_cache_spu_period" UNIQUE ("spu_id", "period");

-- -----------------------------------------------------------
-- product_subscription
-- -----------------------------------------------------------
CREATE TABLE "product_subscription" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "spu_id" BIGINT NOT NULL,
    "price_up_threshold" DECIMAL(8,2),
    "price_down_threshold" DECIMAL(8,2),
    "status" VARCHAR(20) DEFAULT 'ACTIVE',
    "last_notify_at" TIMESTAMP,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "product_subscription" IS '商品行情订阅表（旗舰版）';
COMMENT ON COLUMN "product_subscription"."user_id" IS '订阅用户';
COMMENT ON COLUMN "product_subscription"."spu_id" IS '商品SPU';
COMMENT ON COLUMN "product_subscription"."price_up_threshold" IS '涨价预警阈值(%)';
COMMENT ON COLUMN "product_subscription"."price_down_threshold" IS '降价预警阈值(%)';
COMMENT ON COLUMN "product_subscription"."status" IS '状态: ACTIVE订阅中 / PAUSED已暂停';
COMMENT ON COLUMN "product_subscription"."last_notify_at" IS '上次通知时间';
ALTER TABLE "product_subscription" ADD CONSTRAINT "uk_product_subscription_user_spu" UNIQUE ("user_id", "spu_id");

-- -----------------------------------------------------------
-- supplier_review
-- -----------------------------------------------------------
CREATE TABLE "supplier_review" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL,
    "supplier_id" BIGINT NOT NULL,
    "buyer_id" BIGINT NOT NULL,
    "quality_score" SMALLINT NOT NULL,
    "delivery_score" SMALLINT NOT NULL,
    "service_score" SMALLINT NOT NULL,
    "review_content" VARCHAR(1000),
    "review_images" JSONB,
    "is_anonymous" SMALLINT DEFAULT 0,
    "reply_content" VARCHAR(1000),
    "reply_at" TIMESTAMP,
    "appeal_content" VARCHAR(1000),
    "appeal_status" VARCHAR(20),
    "status" VARCHAR(20) DEFAULT 'PUBLISHED',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "supplier_review" IS '供应商评价表（旗舰版）';
COMMENT ON COLUMN "supplier_review"."order_id" IS '订单ID';
COMMENT ON COLUMN "supplier_review"."supplier_id" IS '供应商ID';
COMMENT ON COLUMN "supplier_review"."buyer_id" IS '评价人（门店）';
COMMENT ON COLUMN "supplier_review"."quality_score" IS '商品质量评分 1-5';
COMMENT ON COLUMN "supplier_review"."delivery_score" IS '配送时效评分 1-5';
COMMENT ON COLUMN "supplier_review"."service_score" IS '服务态度评分 1-5';
COMMENT ON COLUMN "supplier_review"."review_content" IS '评价内容';
COMMENT ON COLUMN "supplier_review"."review_images" IS '评价图片';
COMMENT ON COLUMN "supplier_review"."is_anonymous" IS '是否匿名 1是 0否';
COMMENT ON COLUMN "supplier_review"."reply_content" IS '供应商回复';
COMMENT ON COLUMN "supplier_review"."reply_at" IS '回复时间';
COMMENT ON COLUMN "supplier_review"."appeal_content" IS '申诉内容';
COMMENT ON COLUMN "supplier_review"."appeal_status" IS '申诉状态: NONE无 / PENDING待处理 / ACCEPTED已受理 / REJECTED已驳回';
COMMENT ON COLUMN "supplier_review"."status" IS '状态: PUBLISHED已发布 / HIDDEN已隐藏';
CREATE INDEX "idx_supplier_review_supplier" ON "supplier_review" ("supplier_id");
CREATE INDEX "idx_supplier_review_order" ON "supplier_review" ("order_id");
CREATE INDEX "idx_supplier_review_scores" ON "supplier_review" ("quality_score", "delivery_score", "service_score");

-- -----------------------------------------------------------
-- audit_log
-- -----------------------------------------------------------
CREATE TABLE "audit_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT,
    "company_id" BIGINT,
    "event_type" VARCHAR(50) NOT NULL,
    "event_detail" TEXT,
    "target_type" VARCHAR(50),
    "target_id" BIGINT,
    "ip_address" VARCHAR(50),
    "user_agent" VARCHAR(500),
    "geo_location" VARCHAR(200),
    "risk_level" VARCHAR(20) DEFAULT 'LOW',
    "result" VARCHAR(20) DEFAULT 'SUCCESS',
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE "audit_log" IS '审计日志表（旗舰版）';
COMMENT ON COLUMN "audit_log"."user_id" IS '操作人';
COMMENT ON COLUMN "audit_log"."company_id" IS '所属公司';
COMMENT ON COLUMN "audit_log"."event_type" IS '事件类型: LOGIN登录 / LOGOUT登出 / PERM_CHANGE权限变更 / SENSITIVE敏感操作 / ABNORMAL异常行为';
COMMENT ON COLUMN "audit_log"."event_detail" IS '事件详情';
COMMENT ON COLUMN "audit_log"."target_type" IS '操作对象类型';
COMMENT ON COLUMN "audit_log"."target_id" IS '操作对象ID';
COMMENT ON COLUMN "audit_log"."ip_address" IS 'IP地址';
COMMENT ON COLUMN "audit_log"."user_agent" IS 'UA';
COMMENT ON COLUMN "audit_log"."geo_location" IS '地理位置';
COMMENT ON COLUMN "audit_log"."risk_level" IS '风险等级: LOW低 / MEDIUM中 / HIGH高 / CRITICAL严重';
COMMENT ON COLUMN "audit_log"."result" IS '结果: SUCCESS成功 / FAILED失败 / BLOCKED被拦截';
CREATE INDEX "idx_audit_log_user" ON "audit_log" ("user_id");
CREATE INDEX "idx_audit_log_event" ON "audit_log" ("event_type");
CREATE INDEX "idx_audit_log_risk" ON "audit_log" ("risk_level");
CREATE INDEX "idx_audit_log_created" ON "audit_log" ("created_at");


COMMIT;

-- 共 47 张表
-- 转换说明:
--   AUTO_INCREMENT → GENERATED BY DEFAULT AS IDENTITY
--   TINYINT → SMALLINT
--   DATETIME → TIMESTAMP
--   JSON → JSONB
--   KEY → CREATE INDEX
--   UNIQUE KEY → ALTER TABLE ADD CONSTRAINT UNIQUE
--   ON UPDATE CURRENT_TIMESTAMP → 需单独创建触发器
-- ============================================================
